webserver:
  port: 10160
  host: 0.0.0.0
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"

grpcserver:
  host: 0.0.0.0
  port: 10168

tracing:
  enabled: true
  service: metadata-distributor
  sampler-type: const
  sampler-param: 1
  propagation: b3
  protocol: http
  host: localhost
  port: 14268
  path: /api/traces
  paths:
    - path: "/favicon.ico"
      enabled: false
    - path: "/metrics"
      enabled: false
    - path: "/metrics/vendor"
      enabled: false
    - path: "/metrics/base"
      enabled: false
    - path: "/metrics/application"
      enabled: false
    - path: "/health"
      enabled: false
    - path: "/health/live"
      enabled: false
    - path: "/health/ready"
      enabled: false

pubsub:
  use-emulator: true
  emulator:
    host: localhost
    port: 8538
  credential-provider: emulator
  credentials:
    service-account:
      path: secret/my-service-account-key.json
    compute-engine:
    emulator:
    default:
  admin: true
  metadata-routing:
    - upstream:
        - projectId: dapla
          topic: file-events-1
          subscription: metadata-distributor-catalog
          subscribe: true
          ack-deadline-seconds: 30
          dlq:
            projectId: dapla
            topic: file-events-1-catalog-dlq
            max-redelivery-attempts: 5
            subscription: file-events-1-catalog-dlq-errors
      downstream:
        - projectId: dapla
          topic: catalog-1
    - upstream:
        - projectId: dapla
          topic: file-events-1
          subscription: metadata-distributor-exploration
          subscribe: true
          ack-deadline-seconds: 30
          dlq:
            projectId: dapla
            topic: file-events-1-exploration-dlq
            max-redelivery-attempts: 5
            subscription: file-events-1-exploration-dlq-errors
      downstream:
        - projectId: dapla
          topic: exploration-metadata-1

storage:
  cloud-storage:
    enabled: false
    credential-provider: service-account
    credentials:
      service-account:
        path: secret/my-service-account-key.json
      compute-engine:
      default:

metadatads:
  bypass-validation: false
  format: PKCS12
  keystore: secret/metadata-verifier_keystore.p12
  keyAlias: dataAccessCertificate
  password: changeit
  algorithm: SHA256withRSA
